name: ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker-login
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u elightcap --password-stdin
    
    - uses: actions/checkout@v3
    - name: docker-build
      run: docker build . --file Dockerfile --tag d4bot:$(date +%s)
      
    - uses: actions/checkout@v3
    - name: docker-push
      run: docker push ghcr.io/elightcap/d4bot:latest
    
