name: build & deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        
      - name: docker-login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: elightcap
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: 'Build & push'
        run: |
          docker build . --tag ghcr.io/elightcap/d4bot:latest
          docker push ghcr.io/elightcap/d4bot:latest
